name: CICD

on:
  push:
    branches: [main]

jobs:
  clone_repository:
    name: Clone Repository
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2
      - name: Instal Dependencies
        run: yarn install
      - name: Create Dist
        run: yarn build

  lint_test:
    name: Lint Test
    runs-on: ubuntu-latest
    needs: [clone_repository]
    steps:
      - name: Linting Test
        run: yarn run lint
        env:
          CI: true

  deploy_app:
    name: Deploy App
    runs-on: ubuntu-latest
    needs: [clone_repository, lint_test]
    steps:
      - name: Use Node
        uses: actions/setup-node@v2
        with:
        node-version: "14.x"
      - name: Sync Files
        uses: SamKirkland/FTP-Deploy-Action@4.3.2
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
