name: CICD

on:
  pull_request:
    branches: [main]

jobs:
  deploy_app:
    name: Deploy App
    runs-on: ubuntu-latest
    needs: [lint_test]
    steps:
      - name: Sync Files
        uses: SamKirkland/FTP-Deploy-Action@4.3.2
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
