name: Deploy

on:
  push:
    branches:
      - main

jobs:
  lint_test:
    name: Lint Test
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"

      - name: Instal Dependencies
        run: yarn install

      - name: Create Dist
        run: yarn build

      - name: Linting Test
        run: yarn lint

  deploy_app:
    name: Deploy App
    runs-on: ubuntu-latest
    needs: [lint_test]
    steps:
      - name: Sync Files
        uses: SamKirkland/FTP-Deploy-Action@2.0.0
        with:
          ftp_server: ${{ secrets.FTP_SERVER }}
          ftp_username: ${{ secrets.FTP_USERNAME }}
          ftp_password: ${{ secrets.FTP_PASSWORD }}
          remote_dir: /portfolio/
