name: CICD

on:
  push:

jobs:
  lint_test:
    name: Lint Test
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"

      - name: Instal Dependencies
        run: yarn install

      - name: Create Dist
        run: yarn build

      - name: Linting Test
        run: yarn lint
